server:
  port: 9090
  servlet:
    context-path: /flowable-modeler
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable6?serverTimezone=GMT%2B8
    username: root
    password: root
  aop:
    proxy-target-class: false

#默认的用户

flowable:
  idm:
    app:
      admin:
        user-id: admin
        password: test
        first-name: Test
        last-name: Administrator
        email: admin@flowable.org